### ISSUE TITLE
Difference in behavior between all expired accounts and no accounts

### ISSUE THREAD

**Issue by npm1** [fedidcg/LightweightFedCM#44]
I was wondering what this proposal is for the two scenarios:
* All accounts are expired.
* There have never been stored accounts.

Just wondering since if there is no difference then all expired accounts can be cleared. But if there is a difference I'd want to understand the rationale.

**Comment by bvandersloot-mozilla** [comment]
Accounts do not expire, UI hints do. So, all accounts having their hints expire is equivalent to having accounts with no UI hints, which is different than no stored accounts.

**Comment by npm1** [comment]
My question is what is the difference from the user's point of view.
