### ISSUE TITLE
Is tokenURL being called?

### ISSUE THREAD

**Issue by philsmart** [fedidcg/LightweightFedCM#46]
Hi @bvandersloot-mozilla,

I am playing around with this (thanks). I am storing a credential as follows:

```
 navigator.credentials.store(
          new IdentityCredential({
            id: "person",
            token: JSON.stringify({user: "phil"}),
            effectiveOrigins: ["http://rp.localhost:8080"],
            tokenURL: "http://idp.localhost:8080/idp/assertion",
            uiHint: {
              name: "person",              
              expiresAfter: 60000,
            },
          }));
```

Then retrieving it on the RP with:

```
navigator.credentials
          .get({
            identity: {
              providers: [
                {
                  origin: "http://idp.localhost:8080",
                  loginURL: "http://idp.localhost:8080/idp/idplw"
                },
              ],
            },
          })
```

But I can not see how or when the `tokenURL` gets called. I guessed it might get called once I selected the identity credential from the chooser, but I can not see it happening. 

Maybe it is just how I am implementing it.

**Comment by ekovac** [comment]
I don't think the prototype in Firefox nightly is actually up to date with the recent changes to the explainer yet.

**Comment by ekovac** [comment]
The testing websites linked here: https://github.com/fedidcg/LightweightFedCM/issues/33 should work in Firefox Nightly but don't represent the latest state of the explainer.

**Comment by philsmart** [comment]
No problems. Thanks.

**Comment by philsmart** [comment]
I'll close this, I can track https://github.com/fedidcg/LightweightFedCM/issues/51 and https://github.com/fedidcg/LightweightFedCM/issues/42.
